import type {
  AssistantResponsePayload,
  PersonalizationProfile,
  ResearchArticle,
} from "@/domain/sbl/types";
import { searchLatestResearch } from "@/implementation/research-search";

function buildFallbackAnswer(
  question: string,
  profile: PersonalizationProfile,
  articles: ResearchArticle[],
  query: string,
): AssistantResponsePayload {
  const topArticles = articles.slice(0, 3);

  return {
    answer:
      `Here is a personalized research snapshot for "${question}". ` +
      `Based on your profile (${profile.goal}, ${profile.trainingAge}, ${profile.weeklyFrequency}), ` +
      `the strongest recent literature in this search set points toward nuance over absolutes. ` +
      `Use the cited studies below as the primary source layer, and treat this fallback summary as non-AI guidance until an OPENAI_API_KEY is configured.`,
    bullets: topArticles.map(
      (article) =>
        `${article.title}${article.year ? ` (${article.year})` : ""} from ${article.source} appears relevant to your question.`,
    ),
    cautions: [
      "This fallback answer is not generated by the OpenAI assistant because no OPENAI_API_KEY is configured.",
      "Recent research retrieval can still surface mixed-quality studies, so prioritize meta-analyses and systematic reviews first.",
    ],
    suggestedActions: [
      "Open the top cited articles and compare their actual methods to the claim you are investigating.",
      "Use your personal constraints like recovery, equipment, and training age when interpreting study conclusions.",
    ],
    searchQuery: query,
    articles,
    usedAi: false,
  };
}

export async function generatePersonalizedAssistantAnswer(
  question: string,
  profile: PersonalizationProfile,
): Promise<AssistantResponsePayload> {
  const { query, articles } = await searchLatestResearch(question, profile);

  if (!process.env.OPENAI_API_KEY) {
    return buildFallbackAnswer(question, profile, articles, query);
  }

  const response = await fetch("https://api.openai.com/v1/responses", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: "gpt-5.4-mini",
      input: [
        {
          role: "system",
          content: [
            {
              type: "input_text",
              text:
                "You are an evidence-aware lifting research assistant. Use only the provided article metadata as evidence context. Never claim certainty beyond the supplied studies. Provide personalized but cautious educational guidance, not medical advice.",
            },
          ],
        },
        {
          role: "user",
          content: [
            {
              type: "input_text",
              text: JSON.stringify({
                question,
                profile,
                articles,
              }),
            },
          ],
        },
      ],
      text: {
        format: {
          type: "json_schema",
          name: "assistant_research_answer",
          strict: true,
          schema: {
            type: "object",
            additionalProperties: false,
            properties: {
              answer: { type: "string" },
              bullets: {
                type: "array",
                items: { type: "string" },
              },
              cautions: {
                type: "array",
                items: { type: "string" },
              },
              suggestedActions: {
                type: "array",
                items: { type: "string" },
              },
            },
            required: ["answer", "bullets", "cautions", "suggestedActions"],
          },
        },
      },
    }),
  });

  if (!response.ok) {
    return buildFallbackAnswer(question, profile, articles, query);
  }

  const payload = (await response.json()) as {
    output_text?: string;
  };

  try {
    const parsed = JSON.parse(payload.output_text ?? "{}") as Omit<
      AssistantResponsePayload,
      "searchQuery" | "articles" | "usedAi"
    >;

    return {
      ...parsed,
      searchQuery: query,
      articles,
      usedAi: true,
    };
  } catch {
    return buildFallbackAnswer(question, profile, articles, query);
  }
}
